version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building frontend"
      - mkdir build
      - cp -r * ./build/
  post_build:
    commands:
      - echo "Deploying to S3 bucket: adrian-photo-drive"
      - aws s3 sync ./build s3://adrian-photo-drive --delete
artifacts:
  files:
    - '**/*'
